feat: add checks for resources
ionos-cloud/terraformer pull request #10
Opened 2022-10-28 12:49 UTC by adeatcu-ionos

Details about the reason for which we need to add these checks can be found [here](https://jira.sso.ionos.cloud/browse/SDK-1191).

2022-10-28 14:46 UTC, gabisavu-ionos requested changes

2022-10-28 14:46 UTC, gabisavu-ionos commented on providers/ionoscloud/backup_unit.go
> +		return nil
here should't be returned an error? like an errors.New("no backup unit item found")?
If you return nil, when you call the function somewhere else and it will return nil, it is understand that this function returned no error since the error will be nil

2022-10-28 14:46 UTC, gabisavu-ionos commented on providers/ionoscloud/backup_unit.go
> +	if backupUnitResponse.Items == nil {
you can also check if backupUnitResponse.Items != nil and include in the brackets the code below(backupUnits := *backupUnitResponse.Items and the for loop) and not return nil, because at the end of the function, if everything is fine, is already returning nil

2022-10-28 14:46 UTC, gabisavu-ionos commented on providers/ionoscloud/helpers/helper_dependencies_list.go
> +		return nil, nil
here shouldn't return an error also? to be able to see that no items was found when calling the function?

2022-10-28 14:46 UTC, gabisavu-ionos commented on providers/ionoscloud/nic.go
> +			return nil
same comment as above

2022-10-28 14:46 UTC, gabisavu-ionos commented on providers/ionoscloud/nic.go
> +			}
same comment

2022-10-31 05:41 UTC, adeatcu-ionos commented on providers/ionoscloud/backup_unit.go
> +		return nil
In the beginning, when I discussed with @cristiGuranIonos, we decided to make the checks as they are now and to warn the user only when the `Properties` field or `Properties.Name` is `nil`, but thinking about it twice, it may be necessary to also warn the user that the `Items` field is `nil`. 

> here should't be returned an error? like an errors.New("no backup unit item found")?

No, there is no problem if no backup unit items are found, i.e, when `backupUnitResponse.Items` is empty. But, there is a problem when `backupUnitResponse.Items` is `nil`. When retrieving the items of any kind, we expect a slice, be it empty or with some elements in it, but we expect the slice to be valid, not `nil`.

@cristiGuranIonos @gabisavu-ionos what do you think about this? I noticed that for other resources, `dbass_cluster` for example, we have checks like:
```
if output.Items != nil {
    g.Resources = g.createResources(*output.Items)
}
```
So again, when the `output.Items` is `nil`, we simply ignore the response, but I'm not sure if that is okay, maybe we can have a chat today about this.

2022-10-31 05:50 UTC, adeatcu-ionos commented on providers/ionoscloud/backup_unit.go
> +	if backupUnitResponse.Items == nil {
@gabisavu-ionos yes, that's how the code was written before, but for some files, for example `nic.go`, we have 2 or more get requests and many nested checks and `for`s so the code was harder to read before. I changed the structure for those files (with 2 or more get requests) in order to improve readability and I kept the same structure for the smaller files (with 1 get request), such as `backup_unit.go`.

2022-10-31 05:51 UTC, adeatcu-ionos commented on providers/ionoscloud/helpers/helper_dependencies_list.go
> +		return nil, nil
@gabisavu-ionos won't reply to each of the comments below since they are all about the same topic and the answer is [here](https://github.com/ionos-cloud/terraformer/pull/10#discussion_r1009046501).

2022-10-31 09:35 UTC, gabisavu-ionos approved these changes

2022-11-01 09:39 UTC, cristiGuranIonos approved these changes

2022-11-01 13:38 UTC, gabisavu-ionos approved these changes

2022-11-02 04:48 UTC, merged